apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-chaman
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/add-base-url: "true"
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: "{{$.cluster.domain}}"
    http:
      paths:
      - path: /
        backend:
          serviceName: chaman
          servicePort: 80
