---
# Source: redis-ha/templates/redis-ha-serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaman-redis-ha
  labels:
    heritage: Tiller
    release: chaman
    chart: redis-ha-3.7.1
    app: chaman-redis-ha
