version: '3.3'

services:
  dlake:
    image: ignitial/dlake:${IIOS_DLAKE_VERSION}
    container_name: dlake
    ports:
      - "20989-20999:20989-20999"
    environment:
      - IIOS_REDIS_HOST=redis
      # - IIOS_TRACE_RPC=true
      # - DEBUG=iios:service
      - IIOS_MONGODB_URI=mongodb://mongo:27017
      - IIOS_DBNAME=${IIOS_DBNAME}
      - IIOS_POPULATE=true
      - IIOS_NAMESPACE=${IIOS_NAMESPACE}
      - IIOS_SERVER_HOST=0.0.0.0
      - IIOS_SERVER_PORT=20991
    networks:
      infra:

  auth:
    image: ignitial/auth:${IIOS_AUTH_VERSION}
    container_name: auth
    ports:
      - "20199:20199"
    environment:
      - IIOS_REDIS_HOST=redis
      - IIOS_NAMESPACE=${IIOS_NAMESPACE}
      - IIOS_SERVER_HOST=0.0.0.0
      - IIOS_SERVER_PORT=20199
    networks:
      infra:

  s3:
    image: ignitial/s3:1.0.0
    container_name: s3
    ports:
      - "21200:21200"
    volumes:
      - /home/${USER}/Documents/Projects/iio/services/s3:/opt/s3
    environment:
      - IIOS_REDIS_HOST=redis
      - IIOS_NAMESPACE=${IIOS_NAMESPACE}
      - IIOS_SERVER_HOST=0.0.0.0
      - IIOS_SERVER_PORT=21200
      - IIOS_S3_ENDPOINT=minio
      - IIOS_S3_PORT=9000
      - IIOS_S3_BUCKET=chaman
      - IIOS_S3_SECURE=false
      - IIOS_S3_ACCESS_KEY_ID=G4I3RZP3I2AS7EMWQPMZ
      - IIOS_S3_SECRET_ACCESS_KEY=xMzrrXMtnFEOP/K7MDFRA/bPxRfiCYEXOTOTOYEK
    networks:
      infra:

  lambda:
    image: ignitial/lambda:1.0.0
    container_name: lambda
    ports:
      - "21201:21201"
    volumes:
      - /home/${USER}/Documents/Projects/iio/services/lambda:/opt/lambda
    environment:
      - IIOS_SERVER_HOST_TEST=0.0.0.0
      - IIOS_DOCKER_REGISTRY=localhost:5001
      - IIOS_REDIS_HOST=redis
      - IIOS_NAMESPACE=${IIOS_NAMESPACE}
      - IIOS_SERVER_HOST=0.0.0.0
      - IIOS_SERVER_PORT=21201
    networks:
      infra:

  docker:
    image: ignitial/docker:1.0.0
    container_name: docker
    ports:
      - "21202:21202"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/${USER}/Documents/Projects/iio/services/docker:/opt/docker
    environment:
      # force host docker use
      - IIOS_DOCKER_SOCKET_PATH=/var/run/docker.sock
      - IIOS_REDIS_HOST=redis
      - IIOS_NAMESPACE=${IIOS_NAMESPACE}
      - IIOS_SERVER_HOST=0.0.0.0
      - IIOS_SERVER_PORT=21202
    networks:
      infra:

  influxdb:
    image: influxdb:1.7-alpine
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=ignitialio
      - INFLUXDB_ADMIN_ENABLED=true
    networks:
      infra:

  influx:
    image: ignitial/influx:1.0.0
    container_name: influx
    ports:
      - "21203:21203"
    volumes:
      - /home/${USER}/Documents/Projects/iio/services/influx:/opt/influx
    environment:
      - IIOS_REDIS_HOST=redis
      - IIOS_NAMESPACE=${IIOS_NAMESPACE}
      - IIOS_SERVER_HOST=0.0.0.0
      - IIOS_SERVER_PORT=21203
    networks:
      infra:

  utils:
    image: ignitial/utils:1.0.0
    container_name: utils
    ports:
      - "21204:21204"
    volumes:
      - /home/${USER}/Documents/Projects/iio/services/utils:/opt/utils
    environment:
      - IIOS_REDIS_HOST=redis
      - IIOS_NAMESPACE=${IIOS_NAMESPACE}
      - IIOS_SERVER_HOST=0.0.0.0
      - IIOS_SERVER_PORT=21204
    networks:
      infra:

networks:
  infra:
    external: true
